### ISSUE TITLE
Size 0 texture for HScrollBar and VScrollBar icons

### ISSUE THREAD

**Issue by Smjert** [Calinou/godot-sponza#69]
When loading the project in Godot it prints this error:

> ERROR: texture_set_size_override: Condition ' p_width <= 0 || p_width > 16384 ' is true.
>    At: drivers/gles3/rasterizer_storage_gles3.cpp:1016.

From the editor it sees that there's a texture but it has size 0, it can also be seen in the file in resources/themes/default.tres on line 10681. 
Clearing the texture from the editor so that it's actually <null> should fix the issue.

I'm reporting this here since i don't know if this is has been created by a bug in Godot.

**Comment by Calinou** [comment]
I created the GUI theme by using the "Create from editor theme" feature of Godot 3.0, which is probably what causes this issue.
