### ISSUE TITLE
Settings "anisotropic_filter_level" & "anisotropic_filter_level" seem not setted

### ISSUE THREAD

**Issue by fabriceci** [Calinou/godot-sponza#74]
It's seem those settings (anisotropic filter and voxel con tracing quality) are not setted in `_on_graphics_preset_change` (or I missed something)

**Comment by fabriceci** [comment]
You set the setting with this line: `ProjectSettings.set_setting(setting, value)`

However when I tried to change MSAA (testing) with this method, it does seem to work at runtime. I don't know if this works with anisotropic filter & voxel con tracing quality.

**Comment by Calinou** [comment]
MSAA setting works because I set the value here: https://github.com/Calinou/godot-sponza/blob/master/scripts/settings_gui.gd#L169

Changing project settings at run-time has no effect whatsoever.

**Comment by fabriceci** [comment]
> The MSAA setting works because I set the value here: https://github.com/Calinou/godot-sponza/blob/master/scripts/settings_gui.gd#L169

Yes I know, I wanted to say that I tried the method with MSAA, because visually it's easier to see if there are changes or not.

> Changing project settings at run-time has no effect whatsoever. 

So the issue is correct. Do you know the "runtime equivalent" for "anisotropic_filter_level" & "anisotropic_filter_level" ?

**Comment by Calinou** [comment]
@fabriceci I'm not sure if the anisotropic filtering level can be changed at run-time. Settings that can't be changed at run-time can still be changed after the project is restarted by loading a project settings override file. This can be done by [defining a path in the Project Settings for it](https://docs.godotengine.org/en/latest/classes/class_projectsettings.html#class-projectsettings-property-application-config-project-settings-override), saving this file using the ConfigFile class then restarting the project.

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/godot-sponza/commit/932706fe097ae372729598c7c570b73ba930335f.
