### ISSUE TITLE
GIProbe Failing to "Bake" in godot-sponza demo

### ISSUE THREAD

**Issue by georgewsinger** [Calinou/godot-sponza#75]
I have downloaded godot-sponza and incorporated it into my project's scene graph without any other modifications.

**Problem:** The shadows/lighting are completely messed up. Everything appears dark/lacking color.

I have had this problem with other scene demos in the past. The solution was to find the demo's "GIProbe" node and click the "Bake" button in the GUI demo. For some reason this doesn't work with godot-sponza though. After I click the "Bake" button, the lighting appears to get better for a flicker, and then returns to normal (with no changes in-game either). Here is a video of this happening: https://youtu.be/8x2Y0mvQ5vU

**Other considerations:**

- Baking at run-time (as opposed to in the editor) has the same effect
- I have ensured that the "Sponza" MeshInstance node has "Use in Bake" checked

**Comment by Calinou** [comment]
I've had this issue ever since upgrading the project to Godot 3.1 or so. At this point, it would likely be better to reimport everything from scratch and set things up again.

**Comment by georgewsinger** [comment]
:heavy_check_mark: Switching to BakedLightmap fixed this issue: https://github.com/SimulaVR/godot-sponza Thanks for your help.

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/godot-sponza/commit/05482048abc525fde0fce235557cee8523efb3db.
